curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/durotar.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/horde/solo/troll/hunter' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Horde Durotar.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/mulgore.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/horde/solo/tauren/hunter' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Horde Mulgore.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/tirisfal.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/horde/solo/undead/warlock' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Horde Tirisfal.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/horde.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/horde/solo/undead/warlock' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "12-60 Horde.json"

curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/dunmorogh.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/alliance/solo/dwarf/hunter' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Alliance Dun'Morogh.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/elwynnforest.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/alliance/solo/human/paladin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Alliance Forest.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/teldrassil.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/alliance/solo/nightelf/druid' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "1-12 Alliance Teldrassil.json"
curl 'https://s3-us-west-2.amazonaws.com/cwl-leveling-json/alliance.json' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-CA,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: https://classicwow.live' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://classicwow.live/leveling/alliance/solo/nightelf/druid' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -o "12-60 Alliance.json"
